# 01-2 张量的基本操作
tensor的基本操作：
- 拼接与切分
- 索引


In [1]:
import torch
torch.manual_seed(1)

torch.cat

将张量按维度dim进行拼接

In [3]:
t = torch.ones((2, 3))

print("t:{} shape:{}".format(t, t.shape))

t_0 = torch.cat([t, t], dim=0)
t_1 = torch.cat([t, t, t], dim=1)

print("t_0:{} shape:{}\nt_1:{} shape:{}".format(t_0, t_0.shape, t_1, t_1.shape))

t:tensor([[1., 1., 1.],
        [1., 1., 1.]]) shape:torch.Size([2, 3])
t_0:tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) shape:torch.Size([4, 3])
t_1:tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]]) shape:torch.Size([2, 9])


torch.stack

在新创建的维度dim上进行拼接

In [4]:
t = torch.ones((2, 3))

t_stack = torch.stack([t, t, t], dim=0)

print("\nt_stack:{} shape:{}".format(t_stack, t_stack.shape))


t_stack:tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) shape:torch.Size([3, 2, 3])


torch.chunk

- 将张量按维度dim进行平均切分
- 注意事项：若不能整除，最后一份张量小于其他张量

In [5]:
a = torch.ones((2, 7))  # 7
list_of_tensors = torch.chunk(a, dim=1, chunks=3)   # 3

for idx, t in enumerate(list_of_tensors):
    print("第{}个张量：{}, shape is {}".format(idx+1, t, t.shape))

第1个张量：tensor([[1., 1., 1.],
        [1., 1., 1.]]), shape is torch.Size([2, 3])
第2个张量：tensor([[1., 1., 1.],
        [1., 1., 1.]]), shape is torch.Size([2, 3])
第3个张量：tensor([[1.],
        [1.]]), shape is torch.Size([2, 1])


torch.split

将张量按维度dim进行切分


In [8]:
t = torch.ones((2, 5))

list_of_tensors = torch.split(t, [2, 1, 2], dim=1)
for idx, t in enumerate(list_of_tensors):
    print("第{}个张量：{}, shape is {}".format(idx, t, t.shape))

第0个张量：tensor([[1., 1.],
        [1., 1.]]), shape is torch.Size([2, 2])
第1个张量：tensor([[1.],
        [1.]]), shape is torch.Size([2, 1])
第2个张量：tensor([[1., 1.],
        [1., 1.]]), shape is torch.Size([2, 2])


torch.index_select

在维度dim上，按index索引数据

In [9]:
t = torch.randint(0, 9, size=(3, 3))
idx = torch.tensor([0, 2], dtype=torch.long)    # float
t_select = torch.index_select(t, dim=0, index=idx)
print("t:\n{}\nt_select:\n{}".format(t, t_select))

t:
tensor([[4, 5, 0],
        [5, 7, 1],
        [2, 5, 8]])
t_select:
tensor([[4, 5, 0],
        [2, 5, 8]])


torch.masked_select

按mask中的True进行索引



In [10]:
t = torch.randint(0, 9, size=(3, 3))
mask = t.le(5)  # ge is mean greater than or equal/   gt: greater than  le  lt
t_select = torch.masked_select(t, mask)
print("t:\n{}\nmask:\n{}\nt_select:\n{} ".format(t, mask, t_select))

t:
tensor([[0, 2, 3],
        [1, 8, 4],
        [0, 3, 6]])
mask:
tensor([[ True,  True,  True],
        [ True, False,  True],
        [ True,  True, False]])
t_select:
tensor([0, 2, 3, 1, 4, 0, 3]) 


torch.reshape

变换张量形状,当张量在内存中是连续时，新张量与input共享数据内存

In [11]:
t = torch.randperm(8)
t_reshape = torch.reshape(t, (-1, 2, 2))    # -1
print("t:{}\nt_reshape:\n{}".format(t, t_reshape))

t[0] = 1024
print("t:{}\nt_reshape:\n{}".format(t, t_reshape))
print("t.data 内存地址:{}".format(id(t.data)))
print("t_reshape.data 内存地址:{}".format(id(t_reshape.data)))

t:tensor([2, 0, 1, 6, 3, 4, 7, 5])
t_reshape:
tensor([[[2, 0],
         [1, 6]],

        [[3, 4],
         [7, 5]]])
t:tensor([1024,    0,    1,    6,    3,    4,    7,    5])
t_reshape:
tensor([[[1024,    0],
         [   1,    6]],

        [[   3,    4],
         [   7,    5]]])
t.data 内存地址:139812884680784
t_reshape.data 内存地址:139812884680784


torch.transpose

交换张量的两个维度

In [12]:
t = torch.rand((2, 3, 4))
t_transpose = torch.transpose(t, dim0=1, dim1=2)    # c*h*w     h*w*c
print("t shape:{}\nt_transpose shape: {}".format(t.shape, t_transpose.shape))

t shape:torch.Size([2, 3, 4])
t_transpose shape: torch.Size([2, 4, 3])


torch.squeeze
- 压缩长度为1的维度(轴)
- dim: 若为None，移除所有长度为1的轴；若指定维度，当且仅当该轴长度为1时，可以被移除

In [13]:
t = torch.rand((1, 2, 3, 1))
t_sq = torch.squeeze(t)
t_0 = torch.squeeze(t, dim=0)
t_1 = torch.squeeze(t, dim=1)
print(t.shape)
print(t_sq.shape)
print(t_0.shape)
print(t_1.shape)


torch.Size([1, 2, 3, 1])
torch.Size([2, 3])
torch.Size([2, 3, 1])
torch.Size([1, 2, 3, 1])


torch.add

逐元素计算 input+alpha×other


In [14]:
t_0 = torch.randn((3, 3))
t_1 = torch.ones_like(t_0)
t_add = torch.add(t_0, 10, t_1)

print("t_0:\n{}\nt_1:\n{}\nt_add_10:\n{}".format(t_0, t_1, t_add))

t_0:
tensor([[ 0.2424,  0.8616,  0.0727],
        [ 1.3484, -0.8737, -0.2693],
        [-0.5124, -0.2997,  0.6655]])
t_1:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
t_add_10:
tensor([[10.2424, 10.8616, 10.0727],
        [11.3484,  9.1263,  9.7307],
        [ 9.4876,  9.7003, 10.6655]])
