In [33]:
import numpy as np
import operator

In [34]:
# 建立数据
def createDataSet():
    group = np.array([[1,101],[5,89],[108,5],[115,8]])
    labels = ['Love Story', 'Love Story', 'Action Movie', 'Action Movie']
    return group, labels

In [37]:
group, labels = createDataSet()
print(group)
print(labels)

(4, 2)
[[  1 101]
 [  5  89]
 [108   5]
 [115   8]]
['Love Story', 'Love Story', 'Action Movie', 'Action Movie']


In [12]:
# 测试数据
test = [101,20]

In [44]:
#np.tile()函数将测试数据平铺成和原始数据一致的格式
Mat = np.tile(test, (group.shape[0], 1)) 
print(Mat)

#diffMat计算测试数据和每一类数据之间的差
diffMat = Mat - group
print(diffMat)

[[101  20]
 [101  20]
 [101  20]
 [101  20]]
[[100 -81]
 [ 96 -69]
 [ -7  15]
 [-14  12]]


In [18]:
# sqDiffMat将差值平方
sqDiffMat = diffMat**2
print(sqDiffMat)

[[10000  6561]
 [ 9216  4761]
 [   49   225]
 [  196   144]]


In [45]:
# sqDistances将每一类的差值求和，axis = 1表示横向相加， axis= 0表示纵向相加
sqDistances = sqDiffMat.sum(axis = 1)
print(sqDistances)

[16561 13977   274   340]


In [25]:
# 将差值开方，得到距离
distances = sqDistances**0.5
print(distances)

[128.68954892 118.22436297  16.55294536  18.43908891]


In [48]:
# argsort()将distances矩阵的值按照从小到大进行排序，返回的是每个值在矩阵中的index
sortedDistIndices = distances.argsort()
print(sortedDistIndices)

[2 3 1 0]


In [56]:
classCount = {}
# 确定K近邻的值
k = 3

for i in range(k):
    # 按照排序的索引值，将lables中的元素存入字典中
    voteIlabel = labels[sortedDistIndices[i]]
    print(voteIlabel)
    # 在字典中索引label值，如果没有则返回0，有则值+1
    classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
    print(classCount)

Action Movie
{'Action Movie': 1}
Action Movie
{'Action Movie': 2}
Love Story
{'Action Movie': 2, 'Love Story': 1}


In [61]:
print(classCount.items())
# 排序对象：classCount.items()
# 排序依据：operator.itemgetter(1)表示取待排对象的第二个值作为排序依据（从0开始，所以1表示第二个值）
# reverse = True 表示降序排列（默认是按照升序排列）
sortedClassCount = sorted(classCount.items(),key = operator.itemgetter(1),reverse=True)
print(sortedClassCount[0][0])

dict_items([('Action Movie', 2), ('Love Story', 1)])
Action Movie
